# Generated by Django 2.1.1 on 2018-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180902_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile-pics/default.jpg', upload_to='profile-pics'),
        ),
    ]
